package net.minecraft.server;


public class class_acq {
	public static final class_acm a;
	public static final class_acm b;
	public static final class_acm c;
	public static final class_acm d;
	public static final class_acm e;
	public static final class_abg f;
	public static final class_acm g;
	public static final class_acm h;
	public static final class_acm i;
	public static final class_acm j;
	public static final class_acm k;
	public static final class_acm l;
	public static final class_acm m;
	public static final class_acm n;
	public static final class_acm o;
	public static final class_acm p;
	public static final class_acm q;
	public static final class_acm r;
	public static final class_acm s;
	public static final class_acm t;
	public static final class_acm u;
	public static final class_acm v;
	public static final class_acm w;
	public static final class_acm x;
	public static final class_acm y;
	public static final class_acm z;
	public static final class_acm A;
	public static final class_acm B;
	public static final class_acm C;
	public static final class_acm D;
	public static final class_acm E;
	public static final class_acm F;
	public static final class_acm G;
	public static final class_acm H;
	public static final class_acm I;
	public static final class_acm J;
	public static final class_acm K;
	public static final class_acm L;
	public static final class_acm M;
	public static final class_acm N;
	public static final class_acm O;
	public static final class_acm P;
	public static final class_acm Q;
	public static final class_acm R;
	public static final class_aav S;
	public static final class_aav T;
	public static final class_aav U;
	public static final class_aav V;
	public static final class_aav W;
	public static final class_aav X;
	public static final class_aav Y;
	public static final class_aav Z;
	public static final class_aav aa;
	public static final class_aav ab;
	public static final class_aav ac;
	public static final class_aav ad;
	public static final class_aav ae;
	public static final class_aav af;
	public static final class_aav ag;
	public static final class_aav ah;
	public static final class_aav ai;
	public static final class_aav aj;
	public static final class_aav ak;
	public static final class_aav al;
	public static final class_acm am;
	public static final class_acm an;
	public static final class_acm ao;
	public static final class_acm ap;
	public static final class_acm aq;
	public static final class_acm ar;
	public static final class_acm as;
	public static final class_acm at;
	public static final class_acm au;
	public static final class_acm av;
	public static final class_acm aw;
	public static final class_acm ax;
	public static final class_acm ay;
	public static final class_acm az;
	public static final class_acm aA;
	public static final class_acm aB;
	public static final class_acm aC;
	public static final class_acm aD;
	public static final class_acm aE;
	public static final class_acm aF;
	public static final class_acm aG;
	public static final class_acm aH;
	public static final class_acm aI;
	public static final class_acm aJ;
	public static final class_acm aK;
	public static final class_acm aL;
	public static final class_acm aM;
	public static final class_acm aN;
	public static final class_acm aO;
	public static final class_acm aP;
	public static final class_acm aQ;
	public static final class_acm aR;
	public static final class_acm aS;
	public static final class_acg aT;
	public static final class_acm aU;
	public static final class_acm aV;
	public static final class_acm aW;
	public static final class_acm aX;
	public static final class_acm aY;
	public static final class_acm aZ;
	public static final class_acm ba;
	public static final class_acm bb;
	public static final class_acm bc;
	public static final class_acm bd;
	public static final class_acm be;
	public static final class_acu bf;
	public static final class_adj bg;
	public static final class_acm bh;
	public static final class_acm bi;
	public static final class_acm bj;
	public static final class_acm bk;
	public static final class_acm bl;
	public static final class_acm bm;
	public static final class_acm bn;
	public static final class_acm bo;
	public static final class_acm bp;
	public static final class_acm bq;
	public static final class_acm br;
	public static final class_acm bs;
	public static final class_acm bt;
	public static final class_acm bu;
	public static final class_acm bv;
	public static final class_acm bw;
	public static final class_acm bx;
	public static final class_acm by;
	public static final class_acm bz;
	public static final class_acm bA;
	public static final class_adb bB;
	public static final class_adb bC;
	public static final class_adb bD;
	public static final class_acm bE;
	public static final class_acm bF;
	public static final class_acm bG;
	public static final class_acm bH;
	public static final class_acm bI;
	public static final class_acm bJ;
	public static final class_acm bK;
	public static final class_acm bL;
	public static final class_acm bM;
	public static final class_acm bN;
	public static final class_acm bO;
	public static final class_acm bP;
	public static final class_acm bQ;
	public static final class_acm bR;
	public static final class_acm bS;
	public static final class_acm bT;
	public static final class_acm bU;
	public static final class_acm bV;
	public static final class_acm bW;
	public static final class_acm bX;
	public static final class_acm bY;
	public static final class_acm bZ;
	public static final class_abx ca;
	public static final class_acm cb;
	public static final class_acm cc;
	public static final class_acm cd;
	public static final class_acm ce;
	public static final class_acm cf;
	public static final class_acm cg;
	public static final class_acm ch;
	public static final class_aby ci;
	public static final class_acm cj;
	public static final class_acm ck;
	public static final class_acm cl;
	public static final class_acm cm;
	public static final class_acm cn;
	public static final class_aaw co;
	public static final class_acm cp;
	public static final class_acm cq;
	public static final class_acm cr;
	public static final class_acm cs;
	public static final class_acm ct;
	public static final class_acm cu;
	public static final class_acm cv;
	public static final class_acm cw;
	public static final class_acm cx;
	public static final class_acm cy;
	public static final class_acm cz;
	public static final class_acm cA;
	public static final class_acm cB;
	public static final class_acm cC;
	public static final class_acm cD;
	public static final class_acm cE;
	public static final class_acm cF;
	public static final class_acm cG;
	public static final class_acm cH;
	public static final class_acm cI;
	public static final class_acm cJ;
	public static final class_acm cK;
	public static final class_acm cL;
	public static final class_acm cM;
	public static final class_acm cN;
	public static final class_acm cO;
	public static final class_acm cP;

	private static class_acm a(String var0) {
		class_acm var1 = (class_acm) class_acm.e.c(new class_ke(var0));
		if (var1 == null) {
			throw new IllegalStateException("Invalid Item requested: " + var0);
		} else {
			return var1;
		}
	}

	static {
		if (!class_kh.a()) {
			throw new RuntimeException("Accessed Items before Bootstrap!");
		} else {
			a = a("iron_shovel");
			b = a("iron_pickaxe");
			c = a("iron_axe");
			d = a("flint_and_steel");
			e = a("apple");
			f = (class_abg) a("bow");
			g = a("arrow");
			h = a("spectral_arrow");
			i = a("tipped_arrow");
			j = a("coal");
			k = a("diamond");
			l = a("iron_ingot");
			m = a("gold_ingot");
			n = a("iron_sword");
			o = a("wooden_sword");
			p = a("wooden_shovel");
			q = a("wooden_pickaxe");
			r = a("wooden_axe");
			s = a("stone_sword");
			t = a("stone_shovel");
			u = a("stone_pickaxe");
			v = a("stone_axe");
			w = a("diamond_sword");
			x = a("diamond_shovel");
			y = a("diamond_pickaxe");
			z = a("diamond_axe");
			A = a("stick");
			B = a("bowl");
			C = a("mushroom_stew");
			D = a("golden_sword");
			E = a("golden_shovel");
			F = a("golden_pickaxe");
			G = a("golden_axe");
			H = a("string");
			I = a("feather");
			J = a("gunpowder");
			K = a("wooden_hoe");
			L = a("stone_hoe");
			M = a("iron_hoe");
			N = a("diamond_hoe");
			O = a("golden_hoe");
			P = a("wheat_seeds");
			Q = a("wheat");
			R = a("bread");
			S = (class_aav) a("leather_helmet");
			T = (class_aav) a("leather_chestplate");
			U = (class_aav) a("leather_leggings");
			V = (class_aav) a("leather_boots");
			W = (class_aav) a("chainmail_helmet");
			X = (class_aav) a("chainmail_chestplate");
			Y = (class_aav) a("chainmail_leggings");
			Z = (class_aav) a("chainmail_boots");
			aa = (class_aav) a("iron_helmet");
			ab = (class_aav) a("iron_chestplate");
			ac = (class_aav) a("iron_leggings");
			ad = (class_aav) a("iron_boots");
			ae = (class_aav) a("diamond_helmet");
			af = (class_aav) a("diamond_chestplate");
			ag = (class_aav) a("diamond_leggings");
			ah = (class_aav) a("diamond_boots");
			ai = (class_aav) a("golden_helmet");
			aj = (class_aav) a("golden_chestplate");
			ak = (class_aav) a("golden_leggings");
			al = (class_aav) a("golden_boots");
			am = a("flint");
			an = a("porkchop");
			ao = a("cooked_porkchop");
			ap = a("painting");
			aq = a("golden_apple");
			ar = a("sign");
			as = a("wooden_door");
			at = a("spruce_door");
			au = a("birch_door");
			av = a("jungle_door");
			aw = a("acacia_door");
			ax = a("dark_oak_door");
			ay = a("bucket");
			az = a("water_bucket");
			aA = a("lava_bucket");
			aB = a("minecart");
			aC = a("saddle");
			aD = a("iron_door");
			aE = a("redstone");
			aF = a("snowball");
			aG = a("boat");
			aH = a("leather");
			aI = a("milk_bucket");
			aJ = a("brick");
			aK = a("clay_ball");
			aL = a("reeds");
			aM = a("paper");
			aN = a("book");
			aO = a("slime_ball");
			aP = a("chest_minecart");
			aQ = a("furnace_minecart");
			aR = a("egg");
			aS = a("compass");
			aT = (class_acg) a("fishing_rod");
			aU = a("clock");
			aV = a("glowstone_dust");
			aW = a("fish");
			aX = a("cooked_fish");
			aY = a("dye");
			aZ = a("bone");
			ba = a("sugar");
			bb = a("cake");
			bc = a("bed");
			bd = a("repeater");
			be = a("cookie");
			bf = (class_acu) a("filled_map");
			bg = (class_adj) a("shears");
			bh = a("melon");
			bi = a("pumpkin_seeds");
			bj = a("melon_seeds");
			bk = a("beef");
			bl = a("cooked_beef");
			bm = a("chicken");
			bn = a("cooked_chicken");
			bo = a("mutton");
			bp = a("cooked_mutton");
			bq = a("rabbit");
			br = a("cooked_rabbit");
			bs = a("rabbit_stew");
			bt = a("rabbit_foot");
			bu = a("rabbit_hide");
			bv = a("rotten_flesh");
			bw = a("ender_pearl");
			bx = a("blaze_rod");
			by = a("ghast_tear");
			bz = a("gold_nugget");
			bA = a("nether_wart");
			bB = (class_adb) a("potion");
			bC = (class_adb) a("splash_potion");
			bD = (class_adb) a("lingering_potion");
			bE = a("glass_bottle");
			bF = a("dragon_breath");
			bG = a("spider_eye");
			bH = a("fermented_spider_eye");
			bI = a("blaze_powder");
			bJ = a("magma_cream");
			bK = a("brewing_stand");
			bL = a("cauldron");
			bM = a("ender_eye");
			bN = a("speckled_melon");
			bO = a("spawn_egg");
			bP = a("experience_bottle");
			bQ = a("fire_charge");
			bR = a("writable_book");
			bS = a("written_book");
			bT = a("emerald");
			bU = a("item_frame");
			bV = a("flower_pot");
			bW = a("carrot");
			bX = a("potato");
			bY = a("baked_potato");
			bZ = a("poisonous_potato");
			ca = (class_abx) a("map");
			cb = a("golden_carrot");
			cc = a("skull");
			cd = a("carrot_on_a_stick");
			ce = a("nether_star");
			cf = a("pumpkin_pie");
			cg = a("fireworks");
			ch = a("firework_charge");
			ci = (class_aby) a("enchanted_book");
			cj = a("comparator");
			ck = a("netherbrick");
			cl = a("quartz");
			cm = a("tnt_minecart");
			cn = a("hopper_minecart");
			co = (class_aaw) a("armor_stand");
			cp = a("iron_horse_armor");
			cq = a("golden_horse_armor");
			cr = a("diamond_horse_armor");
			cs = a("lead");
			ct = a("name_tag");
			cu = a("command_block_minecart");
			cv = a("record_13");
			cw = a("record_cat");
			cx = a("record_blocks");
			cy = a("record_chirp");
			cz = a("record_far");
			cA = a("record_mall");
			cB = a("record_mellohi");
			cC = a("record_stal");
			cD = a("record_strad");
			cE = a("record_ward");
			cF = a("record_11");
			cG = a("record_wait");
			cH = a("prismarine_shard");
			cI = a("prismarine_crystals");
			cJ = a("banner");
			cK = a("shield");
			cL = a("chorus_fruit");
			cM = a("chorus_fruit_popped");
			cN = a("beetroot_seeds");
			cO = a("beetroot");
			cP = a("beetroot_soup");
		}
	}
}
