package net.minecraft.server;

import net.minecraft.server.class_agg;
import net.minecraft.server.class_agj;
import net.minecraft.server.class_ago;
import net.minecraft.server.class_agq;
import net.minecraft.server.class_agt;
import net.minecraft.server.class_agu;
import net.minecraft.server.class_ahb;
import net.minecraft.server.class_ahe;
import net.minecraft.server.class_ahf;
import net.minecraft.server.class_ahm;
import net.minecraft.server.class_ahp;
import net.minecraft.server.class_aib;
import net.minecraft.server.class_aic;
import net.minecraft.server.class_aik;
import net.minecraft.server.class_aio;
import net.minecraft.server.class_aiu;
import net.minecraft.server.class_aja;
import net.minecraft.server.class_ajj;
import net.minecraft.server.class_ajx;
import net.minecraft.server.class_akk;
import net.minecraft.server.class_akn;
import net.minecraft.server.class_ako;
import net.minecraft.server.class_akq;
import net.minecraft.server.class_akv;
import net.minecraft.server.class_alb;
import net.minecraft.server.class_alc;
import net.minecraft.server.class_alf;
import net.minecraft.server.class_alm;
import net.minecraft.server.class_alt;
import net.minecraft.server.class_ane;
import net.minecraft.server.class_anf;
import net.minecraft.server.class_anh;
import net.minecraft.server.class_jz;
import net.minecraft.server.class_kc;

public class class_agk {
   public static final class_agj a;
   public static final class_agj b;
   public static final class_aik c;
   public static final class_agj d;
   public static final class_agj e;
   public static final class_agj f;
   public static final class_agj g;
   public static final class_agj h;
   public static final class_ahp i;
   public static final class_alf j;
   public static final class_ahp k;
   public static final class_alf l;
   public static final class_akq m;
   public static final class_agj n;
   public static final class_agj o;
   public static final class_agj p;
   public static final class_agj q;
   public static final class_agj r;
   public static final class_agj s;
   public static final class_aja t;
   public static final class_aja u;
   public static final class_agj v;
   public static final class_agj w;
   public static final class_agj x;
   public static final class_agj y;
   public static final class_agj z;
   public static final class_agj A;
   public static final class_agj B;
   public static final class_agj C;
   public static final class_agj D;
   public static final class_agj E;
   public static final class_ane F;
   public static final class_agj G;
   public static final class_alm H;
   public static final class_ahf I;
   public static final class_ane J;
   public static final class_anf K;
   public static final class_agj L;
   public static final class_anh M;
   public static final class_aic N;
   public static final class_aic O;
   public static final class_ago P;
   public static final class_ago Q;
   public static final class_agj R;
   public static final class_agj S;
   public static final class_aio T;
   public static final class_aio U;
   public static final class_agj V;
   public static final class_agj W;
   public static final class_agj X;
   public static final class_agj Y;
   public static final class_agj Z;
   public static final class_agj aa;
   public static final class_aib ab;
   public static final class_agj ac;
   public static final class_agj ad;
   public static final class_agu ae;
   public static final class_akk af;
   public static final class_agj ag;
   public static final class_agj ah;
   public static final class_agj ai;
   public static final class_agj aj;
   public static final class_agj ak;
   public static final class_agj al;
   public static final class_agj am;
   public static final class_agj an;
   public static final class_agj ao;
   public static final class_agj ap;
   public static final class_agj aq;
   public static final class_agj ar;
   public static final class_agj as;
   public static final class_agj at;
   public static final class_agj au;
   public static final class_agj av;
   public static final class_agj aw;
   public static final class_agj ax;
   public static final class_agj ay;
   public static final class_agj az;
   public static final class_agj aA;
   public static final class_agj aB;
   public static final class_agj aC;
   public static final class_agj aD;
   public static final class_agj aE;
   public static final class_agj aF;
   public static final class_agj aG;
   public static final class_agj aH;
   public static final class_agj aI;
   public static final class_agj aJ;
   public static final class_agq aK;
   public static final class_agj aL;
   public static final class_akn aM;
   public static final class_agj aN;
   public static final class_agj aO;
   public static final class_agj aP;
   public static final class_agj aQ;
   public static final class_agj aR;
   public static final class_agj aS;
   public static final class_agj aT;
   public static final class_agj aU;
   public static final class_agj aV;
   public static final class_agj aW;
   public static final class_agj aX;
   public static final class_ajx aY;
   public static final class_agj aZ;
   public static final class_agj ba;
   public static final class_ako bb;
   public static final class_ako bc;
   public static final class_agj bd;
   public static final class_agj be;
   public static final class_agj bf;
   public static final class_agj bg;
   public static final class_agj bh;
   public static final class_agj bi;
   public static final class_agj bj;
   public static final class_agj bk;
   public static final class_agj bl;
   public static final class_agj bm;
   public static final class_agj bn;
   public static final class_agj bo;
   public static final class_agj bp;
   public static final class_agj bq;
   public static final class_agj br;
   public static final class_agj bs;
   public static final class_agj bt;
   public static final class_agj bu;
   public static final class_agj bv;
   public static final class_ajj bw;
   public static final class_agj bx;
   public static final class_agj by;
   public static final class_agj bz;
   public static final class_agj bA;
   public static final class_agj bB;
   public static final class_agj bC;
   public static final class_agj bD;
   public static final class_agt bE;
   public static final class_agj bF;
   public static final class_agj bG;
   public static final class_agj bH;
   public static final class_agj bI;
   public static final class_agj bJ;
   public static final class_agj bK;
   public static final class_aio bL;
   public static final class_aio bM;
   public static final class_agj bN;
   public static final class_agj bO;
   public static final class_agj bP;
   public static final class_agj bQ;
   public static final class_alt bR;
   public static final class_agj bS;
   public static final class_agj bT;
   public static final class_agj bU;
   public static final class_agj bV;
   public static final class_agj bW;
   public static final class_agj bX;
   public static final class_agg bY;
   public static final class_agj bZ;
   public static final class_agj ca;
   public static final class_agj cb;
   public static final class_agj cc;
   public static final class_agj cd;
   public static final class_akv ce;
   public static final class_agj cf;
   public static final class_agj cg;
   public static final class_agj ch;
   public static final class_agj ci;
   public static final class_ahb cj;
   public static final class_ahb ck;
   public static final class_ahe cl;
   public static final class_ahe cm;
   public static final class_agj cn;
   public static final class_agj co;
   public static final class_aiu cp;
   public static final class_agj cq;
   public static final class_agj cr;
   public static final class_agj cs;
   public static final class_agj ct;
   public static final class_agj cu;
   public static final class_agj cv;
   public static final class_agj cw;
   public static final class_agj cx;
   public static final class_agj cy;
   public static final class_agj cz;
   public static final class_agj cA;
   public static final class_agj cB;
   public static final class_agj cC;
   public static final class_agj cD;
   public static final class_agj cE;
   public static final class_ahm cF;
   public static final class_alb cG;
   public static final class_alc cH;
   public static final class_agj cI;
   public static final class_agj cJ;
   public static final class_agj cK;
   public static final class_agj cL;
   public static final class_agj cM;
   public static final class_agj cN;
   public static final class_aio cO;
   public static final class_aio cP;
   public static final class_agj cQ;
   public static final class_agj cR;
   public static final class_agj cS;
   public static final class_agj cT;
   public static final class_agj cU;
   public static final class_agj cV;
   public static final class_aio cW;
   public static final class_aio cX;
   public static final class_agj cY;
   public static final class_agj cZ;
   public static final class_agj da;
   public static final class_agj db;
   public static final class_agj dc;

   private static class_agj a(String var0) {
      class_agj var1 = (class_agj)class_agj.c.c(new class_jz(var0));
      if(var1 == null) {
         throw new IllegalStateException("Invalid Block requested: " + var0);
      } else {
         return var1;
      }
   }

   static {
      if(!class_kc.a()) {
         throw new RuntimeException("Accessed Blocks before Bootstrap!");
      } else {
         a = a("air");
         b = a("stone");
         c = (class_aik)a("grass");
         d = a("dirt");
         e = a("cobblestone");
         f = a("planks");
         g = a("sapling");
         h = a("bedrock");
         i = (class_ahp)a("flowing_water");
         j = (class_alf)a("water");
         k = (class_ahp)a("flowing_lava");
         l = (class_alf)a("lava");
         m = (class_akq)a("sand");
         n = a("gravel");
         o = a("gold_ore");
         p = a("iron_ore");
         q = a("coal_ore");
         r = a("log");
         s = a("log2");
         t = (class_aja)a("leaves");
         u = (class_aja)a("leaves2");
         v = a("sponge");
         w = a("glass");
         x = a("lapis_ore");
         y = a("lapis_block");
         z = a("dispenser");
         A = a("sandstone");
         B = a("noteblock");
         C = a("bed");
         D = a("golden_rail");
         E = a("detector_rail");
         F = (class_ane)a("sticky_piston");
         G = a("web");
         H = (class_alm)a("tallgrass");
         I = (class_ahf)a("deadbush");
         J = (class_ane)a("piston");
         K = (class_anf)a("piston_head");
         L = a("wool");
         M = (class_anh)a("piston_extension");
         N = (class_aic)a("yellow_flower");
         O = (class_aic)a("red_flower");
         P = (class_ago)a("brown_mushroom");
         Q = (class_ago)a("red_mushroom");
         R = a("gold_block");
         S = a("iron_block");
         T = (class_aio)a("double_stone_slab");
         U = (class_aio)a("stone_slab");
         V = a("brick_block");
         W = a("tnt");
         X = a("bookshelf");
         Y = a("mossy_cobblestone");
         Z = a("obsidian");
         aa = a("torch");
         ab = (class_aib)a("fire");
         ac = a("mob_spawner");
         ad = a("oak_stairs");
         ae = (class_agu)a("chest");
         af = (class_akk)a("redstone_wire");
         ag = a("diamond_ore");
         ah = a("diamond_block");
         ai = a("crafting_table");
         aj = a("wheat");
         ak = a("farmland");
         al = a("furnace");
         am = a("lit_furnace");
         an = a("standing_sign");
         ao = a("wooden_door");
         ap = a("spruce_door");
         aq = a("birch_door");
         ar = a("jungle_door");
         as = a("acacia_door");
         at = a("dark_oak_door");
         au = a("ladder");
         av = a("rail");
         aw = a("stone_stairs");
         ax = a("wall_sign");
         ay = a("lever");
         az = a("stone_pressure_plate");
         aA = a("iron_door");
         aB = a("wooden_pressure_plate");
         aC = a("redstone_ore");
         aD = a("lit_redstone_ore");
         aE = a("unlit_redstone_torch");
         aF = a("redstone_torch");
         aG = a("stone_button");
         aH = a("snow_layer");
         aI = a("ice");
         aJ = a("snow");
         aK = (class_agq)a("cactus");
         aL = a("clay");
         aM = (class_akn)a("reeds");
         aN = a("jukebox");
         aO = a("fence");
         aP = a("spruce_fence");
         aQ = a("birch_fence");
         aR = a("jungle_fence");
         aS = a("dark_oak_fence");
         aT = a("acacia_fence");
         aU = a("pumpkin");
         aV = a("netherrack");
         aW = a("soul_sand");
         aX = a("glowstone");
         aY = (class_ajx)a("portal");
         aZ = a("lit_pumpkin");
         ba = a("cake");
         bb = (class_ako)a("unpowered_repeater");
         bc = (class_ako)a("powered_repeater");
         bd = a("trapdoor");
         be = a("monster_egg");
         bf = a("stonebrick");
         bg = a("brown_mushroom_block");
         bh = a("red_mushroom_block");
         bi = a("iron_bars");
         bj = a("glass_pane");
         bk = a("melon_block");
         bl = a("pumpkin_stem");
         bm = a("melon_stem");
         bn = a("vine");
         bo = a("fence_gate");
         bp = a("spruce_fence_gate");
         bq = a("birch_fence_gate");
         br = a("jungle_fence_gate");
         bs = a("dark_oak_fence_gate");
         bt = a("acacia_fence_gate");
         bu = a("brick_stairs");
         bv = a("stone_brick_stairs");
         bw = (class_ajj)a("mycelium");
         bx = a("waterlily");
         by = a("nether_brick");
         bz = a("nether_brick_fence");
         bA = a("nether_brick_stairs");
         bB = a("nether_wart");
         bC = a("enchanting_table");
         bD = a("brewing_stand");
         bE = (class_agt)a("cauldron");
         bF = a("end_portal");
         bG = a("end_portal_frame");
         bH = a("end_stone");
         bI = a("dragon_egg");
         bJ = a("redstone_lamp");
         bK = a("lit_redstone_lamp");
         bL = (class_aio)a("double_wooden_slab");
         bM = (class_aio)a("wooden_slab");
         bN = a("cocoa");
         bO = a("sandstone_stairs");
         bP = a("emerald_ore");
         bQ = a("ender_chest");
         bR = (class_alt)a("tripwire_hook");
         bS = a("tripwire");
         bT = a("emerald_block");
         bU = a("spruce_stairs");
         bV = a("birch_stairs");
         bW = a("jungle_stairs");
         bX = a("command_block");
         bY = (class_agg)a("beacon");
         bZ = a("cobblestone_wall");
         ca = a("flower_pot");
         cb = a("carrots");
         cc = a("potatoes");
         cd = a("wooden_button");
         ce = (class_akv)a("skull");
         cf = a("anvil");
         cg = a("trapped_chest");
         ch = a("light_weighted_pressure_plate");
         ci = a("heavy_weighted_pressure_plate");
         cj = (class_ahb)a("unpowered_comparator");
         ck = (class_ahb)a("powered_comparator");
         cl = (class_ahe)a("daylight_detector");
         cm = (class_ahe)a("daylight_detector_inverted");
         cn = a("redstone_block");
         co = a("quartz_ore");
         cp = (class_aiu)a("hopper");
         cq = a("quartz_block");
         cr = a("quartz_stairs");
         cs = a("activator_rail");
         ct = a("dropper");
         cu = a("stained_hardened_clay");
         cv = a("barrier");
         cw = a("iron_trapdoor");
         cx = a("hay_block");
         cy = a("carpet");
         cz = a("hardened_clay");
         cA = a("coal_block");
         cB = a("packed_ice");
         cC = a("acacia_stairs");
         cD = a("dark_oak_stairs");
         cE = a("slime");
         cF = (class_ahm)a("double_plant");
         cG = (class_alb)a("stained_glass");
         cH = (class_alc)a("stained_glass_pane");
         cI = a("prismarine");
         cJ = a("sea_lantern");
         cK = a("standing_banner");
         cL = a("wall_banner");
         cM = a("red_sandstone");
         cN = a("red_sandstone_stairs");
         cO = (class_aio)a("double_stone_slab2");
         cP = (class_aio)a("stone_slab2");
         cQ = a("end_rod");
         cR = a("chorus_plant");
         cS = a("chorus_flower");
         cT = a("purpur_block");
         cU = a("purpur_pillar");
         cV = a("purpur_stairs");
         cW = (class_aio)a("purpur_double_slab");
         cX = (class_aio)a("purpur_slab");
         cY = a("end_bricks");
         cZ = a("beetroots");
         da = a("grass_path");
         db = a("end_gateway");
         dc = a("structure_block");
      }
   }
}
