package net.minecraft.server;

import net.minecraft.server.class_aac;
import net.minecraft.server.class_aad;
import net.minecraft.server.class_aal;
import net.minecraft.server.class_aar;
import net.minecraft.server.class_aax;
import net.minecraft.server.class_abe;
import net.minecraft.server.class_abl;
import net.minecraft.server.MinecraftKey;
import net.minecraft.server.class_kc;
import net.minecraft.server.class_za;
import net.minecraft.server.class_zb;
import net.minecraft.server.class_zl;

public class class_aau {
   public static final class_aar a;
   public static final class_aar b;
   public static final class_aar c;
   public static final class_aar d;
   public static final class_aar e;
   public static final class_zl f;
   public static final class_aar g;
   public static final class_aar h;
   public static final class_aar i;
   public static final class_aar j;
   public static final class_aar k;
   public static final class_aar l;
   public static final class_aar m;
   public static final class_aar n;
   public static final class_aar o;
   public static final class_aar p;
   public static final class_aar q;
   public static final class_aar r;
   public static final class_aar s;
   public static final class_aar t;
   public static final class_aar u;
   public static final class_aar v;
   public static final class_aar w;
   public static final class_aar x;
   public static final class_aar y;
   public static final class_aar z;
   public static final class_aar A;
   public static final class_aar B;
   public static final class_aar C;
   public static final class_aar D;
   public static final class_aar E;
   public static final class_aar F;
   public static final class_aar G;
   public static final class_aar H;
   public static final class_aar I;
   public static final class_aar J;
   public static final class_aar K;
   public static final class_aar L;
   public static final class_aar M;
   public static final class_aar N;
   public static final class_aar O;
   public static final class_aar P;
   public static final class_aar Q;
   public static final class_aar R;
   public static final class_za S;
   public static final class_za T;
   public static final class_za U;
   public static final class_za V;
   public static final class_za W;
   public static final class_za X;
   public static final class_za Y;
   public static final class_za Z;
   public static final class_za aa;
   public static final class_za ab;
   public static final class_za ac;
   public static final class_za ad;
   public static final class_za ae;
   public static final class_za af;
   public static final class_za ag;
   public static final class_za ah;
   public static final class_za ai;
   public static final class_za aj;
   public static final class_za ak;
   public static final class_za al;
   public static final class_aar am;
   public static final class_aar an;
   public static final class_aar ao;
   public static final class_aar ap;
   public static final class_aar aq;
   public static final class_aar ar;
   public static final class_aar as;
   public static final class_aar at;
   public static final class_aar au;
   public static final class_aar av;
   public static final class_aar aw;
   public static final class_aar ax;
   public static final class_aar ay;
   public static final class_aar az;
   public static final class_aar aA;
   public static final class_aar aB;
   public static final class_aar aC;
   public static final class_aar aD;
   public static final class_aar aE;
   public static final class_aar aF;
   public static final class_aar aG;
   public static final class_aar aH;
   public static final class_aar aI;
   public static final class_aar aJ;
   public static final class_aar aK;
   public static final class_aar aL;
   public static final class_aar aM;
   public static final class_aar aN;
   public static final class_aar aO;
   public static final class_aar aP;
   public static final class_aar aQ;
   public static final class_aar aR;
   public static final class_aar aS;
   public static final class_aal aT;
   public static final class_aar aU;
   public static final class_aar aV;
   public static final class_aar aW;
   public static final class_aar aX;
   public static final class_aar aY;
   public static final class_aar aZ;
   public static final class_aar ba;
   public static final class_aar bb;
   public static final class_aar bc;
   public static final class_aar bd;
   public static final class_aar be;
   public static final class_aax bf;
   public static final class_abl bg;
   public static final class_aar bh;
   public static final class_aar bi;
   public static final class_aar bj;
   public static final class_aar bk;
   public static final class_aar bl;
   public static final class_aar bm;
   public static final class_aar bn;
   public static final class_aar bo;
   public static final class_aar bp;
   public static final class_aar bq;
   public static final class_aar br;
   public static final class_aar bs;
   public static final class_aar bt;
   public static final class_aar bu;
   public static final class_aar bv;
   public static final class_aar bw;
   public static final class_aar bx;
   public static final class_aar by;
   public static final class_aar bz;
   public static final class_aar bA;
   public static final class_abe bB;
   public static final class_abe bC;
   public static final class_aar bD;
   public static final class_aar bE;
   public static final class_aar bF;
   public static final class_aar bG;
   public static final class_aar bH;
   public static final class_aar bI;
   public static final class_aar bJ;
   public static final class_aar bK;
   public static final class_aar bL;
   public static final class_aar bM;
   public static final class_aar bN;
   public static final class_aar bO;
   public static final class_aar bP;
   public static final class_aar bQ;
   public static final class_aar bR;
   public static final class_aar bS;
   public static final class_aar bT;
   public static final class_aar bU;
   public static final class_aar bV;
   public static final class_aar bW;
   public static final class_aar bX;
   public static final class_aac bY;
   public static final class_aar bZ;
   public static final class_aar ca;
   public static final class_aar cb;
   public static final class_aar cc;
   public static final class_aar cd;
   public static final class_aar ce;
   public static final class_aar cf;
   public static final class_aad cg;
   public static final class_aar ch;
   public static final class_aar ci;
   public static final class_aar cj;
   public static final class_aar ck;
   public static final class_aar cl;
   public static final class_zb cm;
   public static final class_aar cn;
   public static final class_aar co;
   public static final class_aar cp;
   public static final class_aar cq;
   public static final class_aar cr;
   public static final class_aar cs;
   public static final class_aar ct;
   public static final class_aar cu;
   public static final class_aar cv;
   public static final class_aar cw;
   public static final class_aar cx;
   public static final class_aar cy;
   public static final class_aar cz;
   public static final class_aar cA;
   public static final class_aar cB;
   public static final class_aar cC;
   public static final class_aar cD;
   public static final class_aar cE;
   public static final class_aar cF;
   public static final class_aar cG;
   public static final class_aar cH;
   public static final class_aar cI;
   public static final class_aar cJ;
   public static final class_aar cK;
   public static final class_aar cL;
   public static final class_aar cM;

   private static class_aar a(String var0) {
      class_aar var1 = (class_aar)class_aar.e.get(new MinecraftKey(var0));
      if(var1 == null) {
         throw new IllegalStateException("Invalid Item requested: " + var0);
      } else {
         return var1;
      }
   }

   static {
      if(!class_kc.a()) {
         throw new RuntimeException("Accessed Items before Bootstrap!");
      } else {
         a = a("iron_shovel");
         b = a("iron_pickaxe");
         c = a("iron_axe");
         d = a("flint_and_steel");
         e = a("apple");
         f = (class_zl)a("bow");
         g = a("arrow");
         h = a("spectral_arrow");
         i = a("tipped_arrow");
         j = a("coal");
         k = a("diamond");
         l = a("iron_ingot");
         m = a("gold_ingot");
         n = a("iron_sword");
         o = a("wooden_sword");
         p = a("wooden_shovel");
         q = a("wooden_pickaxe");
         r = a("wooden_axe");
         s = a("stone_sword");
         t = a("stone_shovel");
         u = a("stone_pickaxe");
         v = a("stone_axe");
         w = a("diamond_sword");
         x = a("diamond_shovel");
         y = a("diamond_pickaxe");
         z = a("diamond_axe");
         A = a("stick");
         B = a("bowl");
         C = a("mushroom_stew");
         D = a("golden_sword");
         E = a("golden_shovel");
         F = a("golden_pickaxe");
         G = a("golden_axe");
         H = a("string");
         I = a("feather");
         J = a("gunpowder");
         K = a("wooden_hoe");
         L = a("stone_hoe");
         M = a("iron_hoe");
         N = a("diamond_hoe");
         O = a("golden_hoe");
         P = a("wheat_seeds");
         Q = a("wheat");
         R = a("bread");
         S = (class_za)a("leather_helmet");
         T = (class_za)a("leather_chestplate");
         U = (class_za)a("leather_leggings");
         V = (class_za)a("leather_boots");
         W = (class_za)a("chainmail_helmet");
         X = (class_za)a("chainmail_chestplate");
         Y = (class_za)a("chainmail_leggings");
         Z = (class_za)a("chainmail_boots");
         aa = (class_za)a("iron_helmet");
         ab = (class_za)a("iron_chestplate");
         ac = (class_za)a("iron_leggings");
         ad = (class_za)a("iron_boots");
         ae = (class_za)a("diamond_helmet");
         af = (class_za)a("diamond_chestplate");
         ag = (class_za)a("diamond_leggings");
         ah = (class_za)a("diamond_boots");
         ai = (class_za)a("golden_helmet");
         aj = (class_za)a("golden_chestplate");
         ak = (class_za)a("golden_leggings");
         al = (class_za)a("golden_boots");
         am = a("flint");
         an = a("porkchop");
         ao = a("cooked_porkchop");
         ap = a("painting");
         aq = a("golden_apple");
         ar = a("sign");
         as = a("wooden_door");
         at = a("spruce_door");
         au = a("birch_door");
         av = a("jungle_door");
         aw = a("acacia_door");
         ax = a("dark_oak_door");
         ay = a("bucket");
         az = a("water_bucket");
         aA = a("lava_bucket");
         aB = a("minecart");
         aC = a("saddle");
         aD = a("iron_door");
         aE = a("redstone");
         aF = a("snowball");
         aG = a("boat");
         aH = a("leather");
         aI = a("milk_bucket");
         aJ = a("brick");
         aK = a("clay_ball");
         aL = a("reeds");
         aM = a("paper");
         aN = a("book");
         aO = a("slime_ball");
         aP = a("chest_minecart");
         aQ = a("furnace_minecart");
         aR = a("egg");
         aS = a("compass");
         aT = (class_aal)a("fishing_rod");
         aU = a("clock");
         aV = a("glowstone_dust");
         aW = a("fish");
         aX = a("cooked_fish");
         aY = a("dye");
         aZ = a("bone");
         ba = a("sugar");
         bb = a("cake");
         bc = a("bed");
         bd = a("repeater");
         be = a("cookie");
         bf = (class_aax)a("filled_map");
         bg = (class_abl)a("shears");
         bh = a("melon");
         bi = a("pumpkin_seeds");
         bj = a("melon_seeds");
         bk = a("beef");
         bl = a("cooked_beef");
         bm = a("chicken");
         bn = a("cooked_chicken");
         bo = a("mutton");
         bp = a("cooked_mutton");
         bq = a("rabbit");
         br = a("cooked_rabbit");
         bs = a("rabbit_stew");
         bt = a("rabbit_foot");
         bu = a("rabbit_hide");
         bv = a("rotten_flesh");
         bw = a("ender_pearl");
         bx = a("blaze_rod");
         by = a("ghast_tear");
         bz = a("gold_nugget");
         bA = a("nether_wart");
         bB = (class_abe)a("potion");
         bC = (class_abe)a("splash_potion");
         bD = a("glass_bottle");
         bE = a("spider_eye");
         bF = a("fermented_spider_eye");
         bG = a("blaze_powder");
         bH = a("magma_cream");
         bI = a("brewing_stand");
         bJ = a("cauldron");
         bK = a("ender_eye");
         bL = a("speckled_melon");
         bM = a("spawn_egg");
         bN = a("experience_bottle");
         bO = a("fire_charge");
         bP = a("writable_book");
         bQ = a("written_book");
         bR = a("emerald");
         bS = a("item_frame");
         bT = a("flower_pot");
         bU = a("carrot");
         bV = a("potato");
         bW = a("baked_potato");
         bX = a("poisonous_potato");
         bY = (class_aac)a("map");
         bZ = a("golden_carrot");
         ca = a("skull");
         cb = a("carrot_on_a_stick");
         cc = a("nether_star");
         cd = a("pumpkin_pie");
         ce = a("fireworks");
         cf = a("firework_charge");
         cg = (class_aad)a("enchanted_book");
         ch = a("comparator");
         ci = a("netherbrick");
         cj = a("quartz");
         ck = a("tnt_minecart");
         cl = a("hopper_minecart");
         cm = (class_zb)a("armor_stand");
         cn = a("iron_horse_armor");
         co = a("golden_horse_armor");
         cp = a("diamond_horse_armor");
         cq = a("lead");
         cr = a("name_tag");
         cs = a("command_block_minecart");
         ct = a("record_13");
         cu = a("record_cat");
         cv = a("record_blocks");
         cw = a("record_chirp");
         cx = a("record_far");
         cy = a("record_mall");
         cz = a("record_mellohi");
         cA = a("record_stal");
         cB = a("record_strad");
         cC = a("record_ward");
         cD = a("record_11");
         cE = a("record_wait");
         cF = a("prismarine_shard");
         cG = a("prismarine_crystals");
         cH = a("banner");
         cI = a("chorus_fruit");
         cJ = a("chorus_fruit_popped");
         cK = a("beetroot_seeds");
         cL = a("beetroot");
         cM = a("beetroot_soup");
      }
   }
}
