package net.minecraft.server;

public class Items {

    public static final Item IRON_SHOVEL;
    public static final Item IRON_PICKAXE;
    public static final Item IRON_AXE;
    public static final Item FLINT_AND_STEEL;
    public static final Item APPLE;
    public static final ItemBow BOW;
    public static final Item ARROW;
    public static final Item SPECTRAL_ARROW;
    public static final Item TIPPED_ARROW;
    public static final Item COAL;
    public static final Item DIAMOND;
    public static final Item IRON_INGOT;
    public static final Item GOLD_INGOT;
    public static final Item IRON_SWORD;
    public static final Item WOODEN_SWORD;
    public static final Item WOODEN_SHOVEL;
    public static final Item WOODEN_PICKAXE;
    public static final Item WOODEN_AXE;
    public static final Item STONE_SWORD;
    public static final Item STONE_SHOVEL;
    public static final Item STONE_PICKAXE;
    public static final Item STONE_AXE;
    public static final Item DIAMOND_SWORD;
    public static final Item DIAMOND_SHOVEL;
    public static final Item DIAMOND_PICKAXE;
    public static final Item DIAMOND_AXE;
    public static final Item STICK;
    public static final Item BOWL;
    public static final Item MUSHROOM_STEW;
    public static final Item GOLDEN_SWORD;
    public static final Item GOLDEN_SHOVEL;
    public static final Item GOLDEN_PICKAXE;
    public static final Item GOLDEN_AXE;
    public static final Item STRING;
    public static final Item FEATHER;
    public static final Item GUNPOWDER;
    public static final Item WOODEN_HOE;
    public static final Item STONE_HOE;
    public static final Item IRON_HOE;
    public static final Item DIAMOND_HOE;
    public static final Item GOLDEN_HOE;
    public static final Item WHEAT_SEEDS;
    public static final Item WHEAT;
    public static final Item BREAD;
    public static final ItemArmor LEATHER_HELMET;
    public static final ItemArmor LEATHER_CHESTPLATE;
    public static final ItemArmor LEATHER_LEGGINGS;
    public static final ItemArmor LEATHER_BOOTS;
    public static final ItemArmor CHAINMAIL_HELMET;
    public static final ItemArmor CHAINMAIL_CHESTPLATE;
    public static final ItemArmor CHAINMAIL_LEGGINGS;
    public static final ItemArmor CHAINMAIL_BOOTS;
    public static final ItemArmor IRON_HELMET;
    public static final ItemArmor IRON_CHESTPLATE;
    public static final ItemArmor IRON_LEGGINGS;
    public static final ItemArmor IRON_BOOTS;
    public static final ItemArmor DIAMOND_HELMET;
    public static final ItemArmor DIAMOND_CHESTPLATE;
    public static final ItemArmor DIAMOND_LEGGINGS;
    public static final ItemArmor DIAMOND_BOOTS;
    public static final ItemArmor GOLDEN_HELMET;
    public static final ItemArmor GOLDEN_CHESTPLATE;
    public static final ItemArmor GOLDEN_LEGGINGS;
    public static final ItemArmor GOLDEN_BOOTS;
    public static final Item FLINT;
    public static final Item PORKCHOP;
    public static final Item COOKED_PORKCHOP;
    public static final Item PAINTING;
    public static final Item GOLDEN_APPLE;
    public static final Item SIGN;
    public static final Item WOODEN_DOOR;
    public static final Item SPRUCE_DOOR;
    public static final Item BIRCH_DOOR;
    public static final Item JUNGLE_DOOR;
    public static final Item ACACIA_DOOR;
    public static final Item DARK_OAK_DOOR;
    public static final Item BUCKET;
    public static final Item WATER_BUCKET;
    public static final Item LAVA_BUCKET;
    public static final Item MINECART;
    public static final Item SADDLE;
    public static final Item IRON_DOOR;
    public static final Item REDSTONE;
    public static final Item SNOWBALL;
    public static final Item BOAT;
    public static final Item LEATHER;
    public static final Item MILK_BUCKET;
    public static final Item BRICK;
    public static final Item CLAY_BALL;
    public static final Item REEDS;
    public static final Item PAPER;
    public static final Item BOOK;
    public static final Item SLIME_BALL;
    public static final Item CHEST_MINECART;
    public static final Item FURNACE_MINECART;
    public static final Item EGG;
    public static final Item COMPASS;
    public static final class_aal FISHING_ROD;
    public static final Item CLOCK;
    public static final Item GLOWSTONE_DUST;
    public static final Item FISH;
    public static final Item COOKED_FISH;
    public static final Item DYE;
    public static final Item BONE;
    public static final Item SUGAR;
    public static final Item CAKE;
    public static final Item BED;
    public static final Item REPEATER;
    public static final Item COOKIE;
    public static final class_aax FILLED_MAP;
    public static final class_abl SHEARS;
    public static final Item MELON;
    public static final Item PUMPKIN_SEEDS;
    public static final Item MELON_SEEDS;
    public static final Item BEEF;
    public static final Item COOKED_BEEF;
    public static final Item CHICKEN;
    public static final Item COOKED_CHICKEN;
    public static final Item MUTTON;
    public static final Item COOKED_MUTTON;
    public static final Item RABBIT;
    public static final Item COOKED_RABBIT;
    public static final Item RABBIT_STEW;
    public static final Item RABBIT_FOOT;
    public static final Item RABBIT_HIDE;
    public static final Item ROTTEN_FLESH;
    public static final Item ENDER_PEARL;
    public static final Item BLAZE_ROD;
    public static final Item GHAST_TEAR;
    public static final Item GOLD_NUGGET;
    public static final Item NETHER_WART;
    public static final ItemPotion POTION;
    public static final ItemPotion SPLASH_POTION;
    public static final Item GLASS_BOTTLE;
    public static final Item SPIDER_EYE;
    public static final Item FERMENTED_SPIDER_EYE;
    public static final Item BLAZE_POWDER;
    public static final Item MAGMA_CREAM;
    public static final Item BREWING_STAND;
    public static final Item CAULDRON;
    public static final Item ENDER_EYE;
    public static final Item SPECKLED_MELON;
    public static final Item SPAWN_EGG;
    public static final Item EXPERIENCE_BOTTLE;
    public static final Item FIRE_CHARGE;
    public static final Item WRITABLE_BOOK;
    public static final Item WRITTEN_BOOK;
    public static final Item EMERALD;
    public static final Item ITEM_FRAME;
    public static final Item FLOWER_POT;
    public static final Item CARROT;
    public static final Item POTATO;
    public static final Item BAKED_POTATO;
    public static final Item POISONOUS_POTATO;
    public static final class_aac MAP;
    public static final Item GOLDEN_CARROT;
    public static final Item SKULL;
    public static final Item CARROT_ON_A_STICK;
    public static final Item NETHER_STAR;
    public static final Item PUMPKIN_PIE;
    public static final Item FIREWORKS;
    public static final Item FIREWORK_CHARGE;
    public static final class_aad ENCHANTED_BOOK;
    public static final Item COMPARATOR;
    public static final Item NETHERBRICK;
    public static final Item QUARTZ;
    public static final Item TNT_MINECART;
    public static final Item HOPPER_MINECART;
    public static final ItemArmorStand ARMOR_STAND;
    public static final Item IRON_HORSE_ARMOR;
    public static final Item GOLDEN_HORSE_ARMOR;
    public static final Item DIAMOND_HORSE_ARMOR;
    public static final Item LEAD;
    public static final Item NAME_TAG;
    public static final Item COMMAND_BLOCK_MINECART;
    public static final Item RECORD_13;
    public static final Item RECORD_CAT;
    public static final Item RECORD_BLOCKS;
    public static final Item RECORD_CHIRP;
    public static final Item RECORD_FAR;
    public static final Item RECORD_MALL;
    public static final Item RECORD_MELLOHI;
    public static final Item RECORD_STAL;
    public static final Item RECORD_STRAD;
    public static final Item RECORD_WARD;
    public static final Item RECORD_11;
    public static final Item RECORD_WAIT;
    public static final Item PRISMARINE_SHARD;
    public static final Item PRISMARINE_CRYSTALS;
    public static final Item BANNER;
    public static final Item CHORUS_FRUIT;
    public static final Item CHORUS_FRUIT_POPPED;
    public static final Item BEETROOT_SEEDS;
    public static final Item BEETROOT;
    public static final Item BEETROOT_SOUP;

    private static Item getByName(String name) {
        Item item = Item.ITEM_REGISTRY.get(new MinecraftKey(name));
        if (item == null) {
            throw new IllegalStateException("Invalid Item requested: " + name);
        } else {
            return item;
        }
    }

    static {
        if (!Bootstrap.isInitDone()) {
            throw new RuntimeException("Accessed Items before Bootstrap!");
        } else {
            IRON_SHOVEL = getByName("iron_shovel");
            IRON_PICKAXE = getByName("iron_pickaxe");
            IRON_AXE = getByName("iron_axe");
            FLINT_AND_STEEL = getByName("flint_and_steel");
            APPLE = getByName("apple");
            BOW = (ItemBow) getByName("bow");
            ARROW = getByName("arrow");
            SPECTRAL_ARROW = getByName("spectral_arrow");
            TIPPED_ARROW = getByName("tipped_arrow");
            COAL = getByName("coal");
            DIAMOND = getByName("diamond");
            IRON_INGOT = getByName("iron_ingot");
            GOLD_INGOT = getByName("gold_ingot");
            IRON_SWORD = getByName("iron_sword");
            WOODEN_SWORD = getByName("wooden_sword");
            WOODEN_SHOVEL = getByName("wooden_shovel");
            WOODEN_PICKAXE = getByName("wooden_pickaxe");
            WOODEN_AXE = getByName("wooden_axe");
            STONE_SWORD = getByName("stone_sword");
            STONE_SHOVEL = getByName("stone_shovel");
            STONE_PICKAXE = getByName("stone_pickaxe");
            STONE_AXE = getByName("stone_axe");
            DIAMOND_SWORD = getByName("diamond_sword");
            DIAMOND_SHOVEL = getByName("diamond_shovel");
            DIAMOND_PICKAXE = getByName("diamond_pickaxe");
            DIAMOND_AXE = getByName("diamond_axe");
            STICK = getByName("stick");
            BOWL = getByName("bowl");
            MUSHROOM_STEW = getByName("mushroom_stew");
            GOLDEN_SWORD = getByName("golden_sword");
            GOLDEN_SHOVEL = getByName("golden_shovel");
            GOLDEN_PICKAXE = getByName("golden_pickaxe");
            GOLDEN_AXE = getByName("golden_axe");
            STRING = getByName("string");
            FEATHER = getByName("feather");
            GUNPOWDER = getByName("gunpowder");
            WOODEN_HOE = getByName("wooden_hoe");
            STONE_HOE = getByName("stone_hoe");
            IRON_HOE = getByName("iron_hoe");
            DIAMOND_HOE = getByName("diamond_hoe");
            GOLDEN_HOE = getByName("golden_hoe");
            WHEAT_SEEDS = getByName("wheat_seeds");
            WHEAT = getByName("wheat");
            BREAD = getByName("bread");
            LEATHER_HELMET = (ItemArmor) getByName("leather_helmet");
            LEATHER_CHESTPLATE = (ItemArmor) getByName("leather_chestplate");
            LEATHER_LEGGINGS = (ItemArmor) getByName("leather_leggings");
            LEATHER_BOOTS = (ItemArmor) getByName("leather_boots");
            CHAINMAIL_HELMET = (ItemArmor) getByName("chainmail_helmet");
            CHAINMAIL_CHESTPLATE = (ItemArmor) getByName("chainmail_chestplate");
            CHAINMAIL_LEGGINGS = (ItemArmor) getByName("chainmail_leggings");
            CHAINMAIL_BOOTS = (ItemArmor) getByName("chainmail_boots");
            IRON_HELMET = (ItemArmor) getByName("iron_helmet");
            IRON_CHESTPLATE = (ItemArmor) getByName("iron_chestplate");
            IRON_LEGGINGS = (ItemArmor) getByName("iron_leggings");
            IRON_BOOTS = (ItemArmor) getByName("iron_boots");
            DIAMOND_HELMET = (ItemArmor) getByName("diamond_helmet");
            DIAMOND_CHESTPLATE = (ItemArmor) getByName("diamond_chestplate");
            DIAMOND_LEGGINGS = (ItemArmor) getByName("diamond_leggings");
            DIAMOND_BOOTS = (ItemArmor) getByName("diamond_boots");
            GOLDEN_HELMET = (ItemArmor) getByName("golden_helmet");
            GOLDEN_CHESTPLATE = (ItemArmor) getByName("golden_chestplate");
            GOLDEN_LEGGINGS = (ItemArmor) getByName("golden_leggings");
            GOLDEN_BOOTS = (ItemArmor) getByName("golden_boots");
            FLINT = getByName("flint");
            PORKCHOP = getByName("porkchop");
            COOKED_PORKCHOP = getByName("cooked_porkchop");
            PAINTING = getByName("painting");
            GOLDEN_APPLE = getByName("golden_apple");
            SIGN = getByName("sign");
            WOODEN_DOOR = getByName("wooden_door");
            SPRUCE_DOOR = getByName("spruce_door");
            BIRCH_DOOR = getByName("birch_door");
            JUNGLE_DOOR = getByName("jungle_door");
            ACACIA_DOOR = getByName("acacia_door");
            DARK_OAK_DOOR = getByName("dark_oak_door");
            BUCKET = getByName("bucket");
            WATER_BUCKET = getByName("water_bucket");
            LAVA_BUCKET = getByName("lava_bucket");
            MINECART = getByName("minecart");
            SADDLE = getByName("saddle");
            IRON_DOOR = getByName("iron_door");
            REDSTONE = getByName("redstone");
            SNOWBALL = getByName("snowball");
            BOAT = getByName("boat");
            LEATHER = getByName("leather");
            MILK_BUCKET = getByName("milk_bucket");
            BRICK = getByName("brick");
            CLAY_BALL = getByName("clay_ball");
            REEDS = getByName("reeds");
            PAPER = getByName("paper");
            BOOK = getByName("book");
            SLIME_BALL = getByName("slime_ball");
            CHEST_MINECART = getByName("chest_minecart");
            FURNACE_MINECART = getByName("furnace_minecart");
            EGG = getByName("egg");
            COMPASS = getByName("compass");
            FISHING_ROD = (class_aal) getByName("fishing_rod");
            CLOCK = getByName("clock");
            GLOWSTONE_DUST = getByName("glowstone_dust");
            FISH = getByName("fish");
            COOKED_FISH = getByName("cooked_fish");
            DYE = getByName("dye");
            BONE = getByName("bone");
            SUGAR = getByName("sugar");
            CAKE = getByName("cake");
            BED = getByName("bed");
            REPEATER = getByName("repeater");
            COOKIE = getByName("cookie");
            FILLED_MAP = (class_aax) getByName("filled_map");
            SHEARS = (class_abl) getByName("shears");
            MELON = getByName("melon");
            PUMPKIN_SEEDS = getByName("pumpkin_seeds");
            MELON_SEEDS = getByName("melon_seeds");
            BEEF = getByName("beef");
            COOKED_BEEF = getByName("cooked_beef");
            CHICKEN = getByName("chicken");
            COOKED_CHICKEN = getByName("cooked_chicken");
            MUTTON = getByName("mutton");
            COOKED_MUTTON = getByName("cooked_mutton");
            RABBIT = getByName("rabbit");
            COOKED_RABBIT = getByName("cooked_rabbit");
            RABBIT_STEW = getByName("rabbit_stew");
            RABBIT_FOOT = getByName("rabbit_foot");
            RABBIT_HIDE = getByName("rabbit_hide");
            ROTTEN_FLESH = getByName("rotten_flesh");
            ENDER_PEARL = getByName("ender_pearl");
            BLAZE_ROD = getByName("blaze_rod");
            GHAST_TEAR = getByName("ghast_tear");
            GOLD_NUGGET = getByName("gold_nugget");
            NETHER_WART = getByName("nether_wart");
            POTION = (ItemPotion) getByName("potion");
            SPLASH_POTION = (ItemPotion) getByName("splash_potion");
            GLASS_BOTTLE = getByName("glass_bottle");
            SPIDER_EYE = getByName("spider_eye");
            FERMENTED_SPIDER_EYE = getByName("fermented_spider_eye");
            BLAZE_POWDER = getByName("blaze_powder");
            MAGMA_CREAM = getByName("magma_cream");
            BREWING_STAND = getByName("brewing_stand");
            CAULDRON = getByName("cauldron");
            ENDER_EYE = getByName("ender_eye");
            SPECKLED_MELON = getByName("speckled_melon");
            SPAWN_EGG = getByName("spawn_egg");
            EXPERIENCE_BOTTLE = getByName("experience_bottle");
            FIRE_CHARGE = getByName("fire_charge");
            WRITABLE_BOOK = getByName("writable_book");
            WRITTEN_BOOK = getByName("written_book");
            EMERALD = getByName("emerald");
            ITEM_FRAME = getByName("item_frame");
            FLOWER_POT = getByName("flower_pot");
            CARROT = getByName("carrot");
            POTATO = getByName("potato");
            BAKED_POTATO = getByName("baked_potato");
            POISONOUS_POTATO = getByName("poisonous_potato");
            MAP = (class_aac) getByName("map");
            GOLDEN_CARROT = getByName("golden_carrot");
            SKULL = getByName("skull");
            CARROT_ON_A_STICK = getByName("carrot_on_a_stick");
            NETHER_STAR = getByName("nether_star");
            PUMPKIN_PIE = getByName("pumpkin_pie");
            FIREWORKS = getByName("fireworks");
            FIREWORK_CHARGE = getByName("firework_charge");
            ENCHANTED_BOOK = (class_aad) getByName("enchanted_book");
            COMPARATOR = getByName("comparator");
            NETHERBRICK = getByName("netherbrick");
            QUARTZ = getByName("quartz");
            TNT_MINECART = getByName("tnt_minecart");
            HOPPER_MINECART = getByName("hopper_minecart");
            ARMOR_STAND = (ItemArmorStand) getByName("armor_stand");
            IRON_HORSE_ARMOR = getByName("iron_horse_armor");
            GOLDEN_HORSE_ARMOR = getByName("golden_horse_armor");
            DIAMOND_HORSE_ARMOR = getByName("diamond_horse_armor");
            LEAD = getByName("lead");
            NAME_TAG = getByName("name_tag");
            COMMAND_BLOCK_MINECART = getByName("command_block_minecart");
            RECORD_13 = getByName("record_13");
            RECORD_CAT = getByName("record_cat");
            RECORD_BLOCKS = getByName("record_blocks");
            RECORD_CHIRP = getByName("record_chirp");
            RECORD_FAR = getByName("record_far");
            RECORD_MALL = getByName("record_mall");
            RECORD_MELLOHI = getByName("record_mellohi");
            RECORD_STAL = getByName("record_stal");
            RECORD_STRAD = getByName("record_strad");
            RECORD_WARD = getByName("record_ward");
            RECORD_11 = getByName("record_11");
            RECORD_WAIT = getByName("record_wait");
            PRISMARINE_SHARD = getByName("prismarine_shard");
            PRISMARINE_CRYSTALS = getByName("prismarine_crystals");
            BANNER = getByName("banner");
            CHORUS_FRUIT = getByName("chorus_fruit");
            CHORUS_FRUIT_POPPED = getByName("chorus_fruit_popped");
            BEETROOT_SEEDS = getByName("beetroot_seeds");
            BEETROOT = getByName("beetroot");
            BEETROOT_SOUP = getByName("beetroot_soup");
        }
    }

}
