package net.minecraft.server;

import net.minecraft.server.class_aac;
import net.minecraft.server.class_aad;
import net.minecraft.server.class_aal;
import net.minecraft.server.Item;
import net.minecraft.server.class_aax;
import net.minecraft.server.class_abe;
import net.minecraft.server.class_abl;
import net.minecraft.server.MinecraftKey;
import net.minecraft.server.Bootstrap;
import net.minecraft.server.class_za;
import net.minecraft.server.class_zb;
import net.minecraft.server.class_zl;

public class Items {

	public static final Item a;
	public static final Item b;
	public static final Item c;
	public static final Item d;
	public static final Item e;
	public static final class_zl f;
	public static final Item g;
	public static final Item h;
	public static final Item i;
	public static final Item j;
	public static final Item k;
	public static final Item l;
	public static final Item m;
	public static final Item n;
	public static final Item o;
	public static final Item p;
	public static final Item q;
	public static final Item r;
	public static final Item s;
	public static final Item t;
	public static final Item u;
	public static final Item v;
	public static final Item w;
	public static final Item x;
	public static final Item y;
	public static final Item z;
	public static final Item A;
	public static final Item B;
	public static final Item C;
	public static final Item D;
	public static final Item E;
	public static final Item F;
	public static final Item G;
	public static final Item H;
	public static final Item I;
	public static final Item J;
	public static final Item K;
	public static final Item L;
	public static final Item M;
	public static final Item N;
	public static final Item O;
	public static final Item P;
	public static final Item Q;
	public static final Item R;
	public static final class_za S;
	public static final class_za T;
	public static final class_za U;
	public static final class_za V;
	public static final class_za W;
	public static final class_za X;
	public static final class_za Y;
	public static final class_za Z;
	public static final class_za aa;
	public static final class_za ab;
	public static final class_za ac;
	public static final class_za ad;
	public static final class_za ae;
	public static final class_za af;
	public static final class_za ag;
	public static final class_za ah;
	public static final class_za ai;
	public static final class_za aj;
	public static final class_za ak;
	public static final class_za al;
	public static final Item am;
	public static final Item an;
	public static final Item ao;
	public static final Item ap;
	public static final Item aq;
	public static final Item ar;
	public static final Item as;
	public static final Item at;
	public static final Item au;
	public static final Item av;
	public static final Item aw;
	public static final Item ax;
	public static final Item ay;
	public static final Item az;
	public static final Item aA;
	public static final Item aB;
	public static final Item aC;
	public static final Item aD;
	public static final Item aE;
	public static final Item aF;
	public static final Item aG;
	public static final Item aH;
	public static final Item aI;
	public static final Item aJ;
	public static final Item aK;
	public static final Item aL;
	public static final Item aM;
	public static final Item aN;
	public static final Item aO;
	public static final Item aP;
	public static final Item aQ;
	public static final Item aR;
	public static final Item aS;
	public static final class_aal aT;
	public static final Item aU;
	public static final Item aV;
	public static final Item aW;
	public static final Item aX;
	public static final Item aY;
	public static final Item aZ;
	public static final Item ba;
	public static final Item bb;
	public static final Item bc;
	public static final Item bd;
	public static final Item be;
	public static final class_aax bf;
	public static final class_abl bg;
	public static final Item bh;
	public static final Item bi;
	public static final Item bj;
	public static final Item bk;
	public static final Item bl;
	public static final Item bm;
	public static final Item bn;
	public static final Item bo;
	public static final Item bp;
	public static final Item bq;
	public static final Item br;
	public static final Item bs;
	public static final Item bt;
	public static final Item bu;
	public static final Item bv;
	public static final Item bw;
	public static final Item bx;
	public static final Item by;
	public static final Item bz;
	public static final Item bA;
	public static final class_abe bB;
	public static final class_abe bC;
	public static final Item bD;
	public static final Item bE;
	public static final Item bF;
	public static final Item bG;
	public static final Item bH;
	public static final Item bI;
	public static final Item bJ;
	public static final Item bK;
	public static final Item bL;
	public static final Item bM;
	public static final Item bN;
	public static final Item bO;
	public static final Item bP;
	public static final Item bQ;
	public static final Item bR;
	public static final Item bS;
	public static final Item bT;
	public static final Item bU;
	public static final Item bV;
	public static final Item bW;
	public static final Item bX;
	public static final class_aac bY;
	public static final Item bZ;
	public static final Item ca;
	public static final Item cb;
	public static final Item cc;
	public static final Item cd;
	public static final Item ce;
	public static final Item cf;
	public static final class_aad cg;
	public static final Item ch;
	public static final Item ci;
	public static final Item cj;
	public static final Item ck;
	public static final Item cl;
	public static final class_zb cm;
	public static final Item cn;
	public static final Item co;
	public static final Item cp;
	public static final Item cq;
	public static final Item cr;
	public static final Item cs;
	public static final Item ct;
	public static final Item cu;
	public static final Item cv;
	public static final Item cw;
	public static final Item cx;
	public static final Item cy;
	public static final Item cz;
	public static final Item cA;
	public static final Item cB;
	public static final Item cC;
	public static final Item cD;
	public static final Item cE;
	public static final Item cF;
	public static final Item cG;
	public static final Item cH;
	public static final Item cI;
	public static final Item cJ;
	public static final Item cK;
	public static final Item cL;
	public static final Item cM;

	private static Item getByName(String name) {
		Item item = Item.ITEM_REGISTRY.get(new MinecraftKey(name));
		if (item == null) {
			throw new IllegalStateException("Invalid Item requested: " + name);
		} else {
			return item;
		}
	}

	static {
		if (!Bootstrap.isInitDone()) {
			throw new RuntimeException("Accessed Items before Bootstrap!");
		} else {
			a = getByName("iron_shovel");
			b = getByName("iron_pickaxe");
			c = getByName("iron_axe");
			d = getByName("flint_and_steel");
			e = getByName("apple");
			f = (class_zl) getByName("bow");
			g = getByName("arrow");
			h = getByName("spectral_arrow");
			i = getByName("tipped_arrow");
			j = getByName("coal");
			k = getByName("diamond");
			l = getByName("iron_ingot");
			m = getByName("gold_ingot");
			n = getByName("iron_sword");
			o = getByName("wooden_sword");
			p = getByName("wooden_shovel");
			q = getByName("wooden_pickaxe");
			r = getByName("wooden_axe");
			s = getByName("stone_sword");
			t = getByName("stone_shovel");
			u = getByName("stone_pickaxe");
			v = getByName("stone_axe");
			w = getByName("diamond_sword");
			x = getByName("diamond_shovel");
			y = getByName("diamond_pickaxe");
			z = getByName("diamond_axe");
			A = getByName("stick");
			B = getByName("bowl");
			C = getByName("mushroom_stew");
			D = getByName("golden_sword");
			E = getByName("golden_shovel");
			F = getByName("golden_pickaxe");
			G = getByName("golden_axe");
			H = getByName("string");
			I = getByName("feather");
			J = getByName("gunpowder");
			K = getByName("wooden_hoe");
			L = getByName("stone_hoe");
			M = getByName("iron_hoe");
			N = getByName("diamond_hoe");
			O = getByName("golden_hoe");
			P = getByName("wheat_seeds");
			Q = getByName("wheat");
			R = getByName("bread");
			S = (class_za) getByName("leather_helmet");
			T = (class_za) getByName("leather_chestplate");
			U = (class_za) getByName("leather_leggings");
			V = (class_za) getByName("leather_boots");
			W = (class_za) getByName("chainmail_helmet");
			X = (class_za) getByName("chainmail_chestplate");
			Y = (class_za) getByName("chainmail_leggings");
			Z = (class_za) getByName("chainmail_boots");
			aa = (class_za) getByName("iron_helmet");
			ab = (class_za) getByName("iron_chestplate");
			ac = (class_za) getByName("iron_leggings");
			ad = (class_za) getByName("iron_boots");
			ae = (class_za) getByName("diamond_helmet");
			af = (class_za) getByName("diamond_chestplate");
			ag = (class_za) getByName("diamond_leggings");
			ah = (class_za) getByName("diamond_boots");
			ai = (class_za) getByName("golden_helmet");
			aj = (class_za) getByName("golden_chestplate");
			ak = (class_za) getByName("golden_leggings");
			al = (class_za) getByName("golden_boots");
			am = getByName("flint");
			an = getByName("porkchop");
			ao = getByName("cooked_porkchop");
			ap = getByName("painting");
			aq = getByName("golden_apple");
			ar = getByName("sign");
			as = getByName("wooden_door");
			at = getByName("spruce_door");
			au = getByName("birch_door");
			av = getByName("jungle_door");
			aw = getByName("acacia_door");
			ax = getByName("dark_oak_door");
			ay = getByName("bucket");
			az = getByName("water_bucket");
			aA = getByName("lava_bucket");
			aB = getByName("minecart");
			aC = getByName("saddle");
			aD = getByName("iron_door");
			aE = getByName("redstone");
			aF = getByName("snowball");
			aG = getByName("boat");
			aH = getByName("leather");
			aI = getByName("milk_bucket");
			aJ = getByName("brick");
			aK = getByName("clay_ball");
			aL = getByName("reeds");
			aM = getByName("paper");
			aN = getByName("book");
			aO = getByName("slime_ball");
			aP = getByName("chest_minecart");
			aQ = getByName("furnace_minecart");
			aR = getByName("egg");
			aS = getByName("compass");
			aT = (class_aal) getByName("fishing_rod");
			aU = getByName("clock");
			aV = getByName("glowstone_dust");
			aW = getByName("fish");
			aX = getByName("cooked_fish");
			aY = getByName("dye");
			aZ = getByName("bone");
			ba = getByName("sugar");
			bb = getByName("cake");
			bc = getByName("bed");
			bd = getByName("repeater");
			be = getByName("cookie");
			bf = (class_aax) getByName("filled_map");
			bg = (class_abl) getByName("shears");
			bh = getByName("melon");
			bi = getByName("pumpkin_seeds");
			bj = getByName("melon_seeds");
			bk = getByName("beef");
			bl = getByName("cooked_beef");
			bm = getByName("chicken");
			bn = getByName("cooked_chicken");
			bo = getByName("mutton");
			bp = getByName("cooked_mutton");
			bq = getByName("rabbit");
			br = getByName("cooked_rabbit");
			bs = getByName("rabbit_stew");
			bt = getByName("rabbit_foot");
			bu = getByName("rabbit_hide");
			bv = getByName("rotten_flesh");
			bw = getByName("ender_pearl");
			bx = getByName("blaze_rod");
			by = getByName("ghast_tear");
			bz = getByName("gold_nugget");
			bA = getByName("nether_wart");
			bB = (class_abe) getByName("potion");
			bC = (class_abe) getByName("splash_potion");
			bD = getByName("glass_bottle");
			bE = getByName("spider_eye");
			bF = getByName("fermented_spider_eye");
			bG = getByName("blaze_powder");
			bH = getByName("magma_cream");
			bI = getByName("brewing_stand");
			bJ = getByName("cauldron");
			bK = getByName("ender_eye");
			bL = getByName("speckled_melon");
			bM = getByName("spawn_egg");
			bN = getByName("experience_bottle");
			bO = getByName("fire_charge");
			bP = getByName("writable_book");
			bQ = getByName("written_book");
			bR = getByName("emerald");
			bS = getByName("item_frame");
			bT = getByName("flower_pot");
			bU = getByName("carrot");
			bV = getByName("potato");
			bW = getByName("baked_potato");
			bX = getByName("poisonous_potato");
			bY = (class_aac) getByName("map");
			bZ = getByName("golden_carrot");
			ca = getByName("skull");
			cb = getByName("carrot_on_a_stick");
			cc = getByName("nether_star");
			cd = getByName("pumpkin_pie");
			ce = getByName("fireworks");
			cf = getByName("firework_charge");
			cg = (class_aad) getByName("enchanted_book");
			ch = getByName("comparator");
			ci = getByName("netherbrick");
			cj = getByName("quartz");
			ck = getByName("tnt_minecart");
			cl = getByName("hopper_minecart");
			cm = (class_zb) getByName("armor_stand");
			cn = getByName("iron_horse_armor");
			co = getByName("golden_horse_armor");
			cp = getByName("diamond_horse_armor");
			cq = getByName("lead");
			cr = getByName("name_tag");
			cs = getByName("command_block_minecart");
			ct = getByName("record_13");
			cu = getByName("record_cat");
			cv = getByName("record_blocks");
			cw = getByName("record_chirp");
			cx = getByName("record_far");
			cy = getByName("record_mall");
			cz = getByName("record_mellohi");
			cA = getByName("record_stal");
			cB = getByName("record_strad");
			cC = getByName("record_ward");
			cD = getByName("record_11");
			cE = getByName("record_wait");
			cF = getByName("prismarine_shard");
			cG = getByName("prismarine_crystals");
			cH = getByName("banner");
			cI = getByName("chorus_fruit");
			cJ = getByName("chorus_fruit_popped");
			cK = getByName("beetroot_seeds");
			cL = getByName("beetroot");
			cM = getByName("beetroot_soup");
		}
	}

}
